### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by msurdi** [qdqmedia/wiggum#1]
I'd like to contribute to your project but I can't Python but I can Typescript Node Webscale and Mongodb.

Can u pls migrate?

p/d: I Can't login 'cause I have no products??? FIX IT!.

**Comment by slok** [comment]
We would never reach an stable version. The release speed of JS stuff is 2456 libs/s, taking that release speed, would let us 212198400 libs/day not integrated in Wiggum. you can contribute, check: http://qdqmedia.github.io/wiggum/contributing/

Thank you :)

p/d: I think you are entering the wrong password, use **12345**
